2020.04.28 14:39:45 LOG5[ui]: stunnel 5.44 on x86_64-pc-linux-gnu platform
2020.04.28 14:39:45 LOG5[ui]: Compiled with OpenSSL 1.1.0g  2 Nov 2017
2020.04.28 14:39:45 LOG5[ui]: Running  with OpenSSL 1.1.1  11 Sep 2018
2020.04.28 14:39:45 LOG5[ui]: Update OpenSSL shared libraries or rebuild stunnel
2020.04.28 14:39:45 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6,SYSTEMD TLS:ENGINE,FIPS,OCSP,PSK,SNI Auth:LIBWRAP
2020.04.28 14:39:45 LOG5[ui]: Reading configuration from file /mnt/d/VSCode/SeniorProject/cloud-backup/cloud_backup/stunnel/dev_https
2020.04.28 14:39:45 LOG5[ui]: UTF-8 byte order mark not detected
2020.04.28 14:39:45 LOG5[ui]: FIPS mode disabled
2020.04.28 14:39:45 LOG4[ui]: Insecure file permissions on stunnel/stunnel.pem
2020.04.28 14:39:45 LOG5[ui]: Configuration successful
2020.04.28 14:39:51 LOG5[0]: Service [https] accepted connection from 127.0.0.1:52282
2020.04.28 14:39:51 LOG5[1]: Service [https] accepted connection from 127.0.0.1:52283
2020.04.28 14:39:51 LOG3[1]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:39:51 LOG3[0]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:39:51 LOG5[1]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:39:51 LOG5[0]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:39:56 LOG5[2]: Service [https] accepted connection from 127.0.0.1:52284
2020.04.28 14:39:56 LOG5[3]: Service [https] accepted connection from 127.0.0.1:52285
2020.04.28 14:39:56 LOG3[3]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:39:56 LOG3[2]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:39:56 LOG5[3]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:39:56 LOG5[4]: Service [https] accepted connection from 127.0.0.1:52286
2020.04.28 14:39:56 LOG5[2]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:39:56 LOG3[4]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:39:56 LOG5[4]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:39:56 LOG5[5]: Service [https] accepted connection from 127.0.0.1:52287
2020.04.28 14:39:58 LOG5[5]: s_connect: connected 127.0.0.1:8001
2020.04.28 14:39:58 LOG5[5]: Service [https] connected remote server from 127.0.0.1:52288
2020.04.28 14:40:45 LOG5[cron]: Updating DH parameters
2020.04.28 14:40:48 LOG5[cron]: DH parameters updated
2020.04.28 14:40:56 LOG3[5]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 14:40:56 LOG5[5]: Connection closed: 7202 byte(s) sent to TLS, 2492 byte(s) sent to socket
2020.04.28 14:41:26 LOG5[6]: Service [https] accepted connection from 127.0.0.1:52312
2020.04.28 14:41:26 LOG5[7]: Service [https] accepted connection from 127.0.0.1:52313
2020.04.28 14:41:26 LOG3[6]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:41:26 LOG3[7]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:41:26 LOG5[8]: Service [https] accepted connection from 127.0.0.1:52314
2020.04.28 14:41:26 LOG5[6]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:41:26 LOG5[7]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:41:26 LOG3[8]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:41:26 LOG5[9]: Service [https] accepted connection from 127.0.0.1:52315
2020.04.28 14:41:26 LOG5[8]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:41:26 LOG5[9]: s_connect: connected 127.0.0.1:8001
2020.04.28 14:41:26 LOG5[9]: Service [https] connected remote server from 127.0.0.1:52316
2020.04.28 14:41:39 LOG5[10]: Service [https] accepted connection from 127.0.0.1:52322
2020.04.28 14:41:39 LOG3[10]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:41:39 LOG5[10]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:41:44 LOG5[11]: Service [https] accepted connection from 127.0.0.1:52323
2020.04.28 14:41:44 LOG3[11]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:41:44 LOG5[11]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:41:52 LOG5[12]: Service [https] accepted connection from 127.0.0.1:52324
2020.04.28 14:41:52 LOG3[12]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:41:52 LOG5[12]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:42:15 LOG3[9]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 14:42:15 LOG5[9]: Connection closed: 81524 byte(s) sent to TLS, 5221 byte(s) sent to socket
2020.04.28 14:42:17 LOG5[13]: Service [https] accepted connection from 127.0.0.1:52332
2020.04.28 14:42:17 LOG5[14]: Service [https] accepted connection from 127.0.0.1:52333
2020.04.28 14:42:17 LOG3[13]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:42:17 LOG3[14]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:42:17 LOG5[13]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:42:17 LOG5[15]: Service [https] accepted connection from 127.0.0.1:52334
2020.04.28 14:42:17 LOG5[14]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:42:17 LOG5[15]: s_connect: connected 127.0.0.1:8001
2020.04.28 14:42:17 LOG5[15]: Service [https] connected remote server from 127.0.0.1:52335
2020.04.28 14:42:18 LOG5[16]: Service [https] accepted connection from 127.0.0.1:52336
2020.04.28 14:42:18 LOG3[16]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:42:18 LOG5[16]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:42:21 LOG5[17]: Service [https] accepted connection from 127.0.0.1:52337
2020.04.28 14:42:21 LOG3[17]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:42:21 LOG5[17]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:42:29 LOG5[18]: Service [https] accepted connection from 127.0.0.1:52339
2020.04.28 14:42:29 LOG3[18]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:42:29 LOG5[18]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:43:59 LOG5[19]: Service [https] accepted connection from 127.0.0.1:52343
2020.04.28 14:43:59 LOG3[19]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:43:59 LOG5[19]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:46:46 LOG3[15]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 14:46:46 LOG5[15]: Connection closed: 83325 byte(s) sent to TLS, 6192 byte(s) sent to socket
2020.04.28 14:47:08 LOG5[20]: Service [https] accepted connection from 127.0.0.1:52409
2020.04.28 14:47:08 LOG5[21]: Service [https] accepted connection from 127.0.0.1:52410
2020.04.28 14:47:08 LOG3[20]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:47:08 LOG3[21]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:47:08 LOG5[22]: Service [https] accepted connection from 127.0.0.1:52411
2020.04.28 14:47:08 LOG5[20]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:47:08 LOG5[21]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:47:08 LOG3[22]: s_connect: connect ::1:8001: Connection refused (111)
2020.04.28 14:47:08 LOG5[22]: s_connect: connected 127.0.0.1:8001
2020.04.28 14:47:08 LOG5[22]: Service [https] connected remote server from 127.0.0.1:52413
2020.04.28 14:47:28 LOG3[22]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 14:47:28 LOG5[22]: Connection closed: 2919 byte(s) sent to TLS, 706 byte(s) sent to socket
2020.04.28 14:47:32 LOG5[23]: Service [https] accepted connection from 127.0.0.1:52419
2020.04.28 14:47:32 LOG5[24]: Service [https] accepted connection from 127.0.0.1:52420
2020.04.28 14:47:32 LOG3[23]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:47:32 LOG3[24]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:47:32 LOG5[23]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:47:32 LOG5[25]: Service [https] accepted connection from 127.0.0.1:52421
2020.04.28 14:47:32 LOG5[24]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:47:32 LOG3[25]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:47:32 LOG5[25]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:47:32 LOG5[26]: Service [https] accepted connection from 127.0.0.1:52422
2020.04.28 14:47:32 LOG3[26]: s_connect: connect ::1:8001: Connection refused (111)
2020.04.28 14:47:32 LOG5[26]: s_connect: connected 127.0.0.1:8001
2020.04.28 14:47:32 LOG5[26]: Service [https] connected remote server from 127.0.0.1:52424
2020.04.28 14:47:36 LOG5[27]: Service [https] accepted connection from 127.0.0.1:52427
2020.04.28 14:47:36 LOG3[27]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:47:36 LOG5[27]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:47:51 LOG3[26]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 14:47:51 LOG5[26]: Connection closed: 5834 byte(s) sent to TLS, 1387 byte(s) sent to socket
2020.04.28 14:47:53 LOG5[28]: Service [https] accepted connection from 127.0.0.1:52433
2020.04.28 14:47:53 LOG5[29]: Service [https] accepted connection from 127.0.0.1:52434
2020.04.28 14:47:53 LOG3[28]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:47:53 LOG3[29]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:47:53 LOG5[30]: Service [https] accepted connection from 127.0.0.1:52435
2020.04.28 14:47:53 LOG5[28]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:47:53 LOG5[29]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:47:53 LOG3[30]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:47:53 LOG5[30]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:47:53 LOG5[31]: Service [https] accepted connection from 127.0.0.1:52436
2020.04.28 14:47:53 LOG5[31]: s_connect: connected 127.0.0.1:8001
2020.04.28 14:47:53 LOG5[31]: Service [https] connected remote server from 127.0.0.1:52437
2020.04.28 14:49:42 LOG3[31]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 14:49:42 LOG5[31]: Connection closed: 73843 byte(s) sent to TLS, 707 byte(s) sent to socket
2020.04.28 14:49:57 LOG5[32]: Service [https] accepted connection from 127.0.0.1:52458
2020.04.28 14:49:57 LOG5[33]: Service [https] accepted connection from 127.0.0.1:52459
2020.04.28 14:49:57 LOG3[32]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:49:57 LOG3[33]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:49:57 LOG5[32]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:49:57 LOG5[33]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:49:57 LOG5[34]: Service [https] accepted connection from 127.0.0.1:52460
2020.04.28 14:49:57 LOG3[34]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:49:57 LOG5[34]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:49:57 LOG5[35]: Service [https] accepted connection from 127.0.0.1:52461
2020.04.28 14:49:57 LOG5[35]: s_connect: connected 127.0.0.1:8001
2020.04.28 14:49:57 LOG5[35]: Service [https] connected remote server from 127.0.0.1:52462
2020.04.28 14:51:41 LOG3[35]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 14:51:41 LOG5[35]: Connection closed: 74025 byte(s) sent to TLS, 707 byte(s) sent to socket
2020.04.28 14:51:48 LOG5[36]: Service [https] accepted connection from 127.0.0.1:52475
2020.04.28 14:51:48 LOG5[37]: Service [https] accepted connection from 127.0.0.1:52476
2020.04.28 14:51:48 LOG3[36]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:51:48 LOG3[37]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:51:48 LOG5[36]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:51:48 LOG5[38]: Service [https] accepted connection from 127.0.0.1:52477
2020.04.28 14:51:49 LOG5[37]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:51:49 LOG3[38]: s_connect: connect ::1:8001: Connection refused (111)
2020.04.28 14:51:49 LOG5[38]: s_connect: connected 127.0.0.1:8001
2020.04.28 14:51:49 LOG5[38]: Service [https] connected remote server from 127.0.0.1:52479
2020.04.28 14:52:43 LOG5[39]: Service [https] accepted connection from 127.0.0.1:52493
2020.04.28 14:52:43 LOG3[39]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:52:43 LOG5[39]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:54:39 LOG3[38]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 14:54:39 LOG5[38]: Connection closed: 148162 byte(s) sent to TLS, 1434 byte(s) sent to socket
2020.04.28 14:54:47 LOG5[40]: Service [https] accepted connection from 127.0.0.1:52560
2020.04.28 14:54:47 LOG5[41]: Service [https] accepted connection from 127.0.0.1:52561
2020.04.28 14:54:47 LOG3[40]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:54:47 LOG3[41]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:54:47 LOG5[40]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:54:47 LOG5[42]: Service [https] accepted connection from 127.0.0.1:52562
2020.04.28 14:54:47 LOG5[41]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:54:47 LOG3[42]: s_connect: connect ::1:8001: Connection refused (111)
2020.04.28 14:54:47 LOG5[42]: s_connect: connected 127.0.0.1:8001
2020.04.28 14:54:47 LOG5[42]: Service [https] connected remote server from 127.0.0.1:52564
2020.04.28 14:57:35 LOG3[42]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 14:57:35 LOG5[42]: Connection closed: 74010 byte(s) sent to TLS, 727 byte(s) sent to socket
2020.04.28 14:57:39 LOG5[43]: Service [https] accepted connection from 127.0.0.1:52579
2020.04.28 14:57:39 LOG3[43]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:57:39 LOG5[43]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:57:41 LOG5[44]: Service [https] accepted connection from 127.0.0.1:52584
2020.04.28 14:57:41 LOG5[45]: Service [https] accepted connection from 127.0.0.1:52585
2020.04.28 14:57:41 LOG3[44]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:57:41 LOG5[44]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:57:41 LOG3[45]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:57:41 LOG5[46]: Service [https] accepted connection from 127.0.0.1:52587
2020.04.28 14:57:41 LOG5[45]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:57:41 LOG3[46]: s_connect: connect ::1:8001: Connection refused (111)
2020.04.28 14:57:41 LOG5[46]: s_connect: connected 127.0.0.1:8001
2020.04.28 14:57:41 LOG5[46]: Service [https] connected remote server from 127.0.0.1:52589
2020.04.28 14:57:47 LOG5[47]: Service [https] accepted connection from 127.0.0.1:52591
2020.04.28 14:57:47 LOG3[47]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:57:47 LOG5[47]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:58:24 LOG5[48]: Service [https] accepted connection from 127.0.0.1:52598
2020.04.28 14:58:24 LOG3[48]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:58:24 LOG5[48]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:59:26 LOG3[46]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 14:59:26 LOG5[46]: Connection closed: 10648 byte(s) sent to TLS, 3814 byte(s) sent to socket
2020.04.28 14:59:33 LOG5[49]: Service [https] accepted connection from 127.0.0.1:52614
2020.04.28 14:59:33 LOG5[50]: Service [https] accepted connection from 127.0.0.1:52615
2020.04.28 14:59:33 LOG3[49]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:59:33 LOG3[50]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:59:33 LOG5[51]: Service [https] accepted connection from 127.0.0.1:52616
2020.04.28 14:59:33 LOG5[49]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:59:33 LOG5[50]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:59:33 LOG5[51]: s_connect: connected 127.0.0.1:8001
2020.04.28 14:59:33 LOG5[51]: Service [https] connected remote server from 127.0.0.1:52617
2020.04.28 14:59:39 LOG5[52]: Service [https] accepted connection from 127.0.0.1:52621
2020.04.28 14:59:39 LOG3[52]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:59:39 LOG5[52]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 14:59:40 LOG5[53]: Service [https] accepted connection from 127.0.0.1:52623
2020.04.28 14:59:40 LOG3[53]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 14:59:40 LOG5[53]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:00:06 LOG3[51]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 15:00:06 LOG5[51]: Connection closed: 6393 byte(s) sent to TLS, 3943 byte(s) sent to socket
2020.04.28 15:00:10 LOG5[54]: Service [https] accepted connection from 127.0.0.1:52634
2020.04.28 15:00:10 LOG5[55]: Service [https] accepted connection from 127.0.0.1:52635
2020.04.28 15:00:10 LOG3[54]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:00:10 LOG3[55]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:00:10 LOG5[56]: Service [https] accepted connection from 127.0.0.1:52636
2020.04.28 15:00:10 LOG5[54]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:00:10 LOG5[55]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:00:10 LOG3[56]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:00:10 LOG5[56]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:00:10 LOG5[57]: Service [https] accepted connection from 127.0.0.1:52637
2020.04.28 15:00:10 LOG5[57]: s_connect: connected 127.0.0.1:8001
2020.04.28 15:00:10 LOG5[57]: Service [https] connected remote server from 127.0.0.1:52638
2020.04.28 15:00:15 LOG5[58]: Service [https] accepted connection from 127.0.0.1:52639
2020.04.28 15:00:15 LOG3[58]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:00:15 LOG5[58]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:00:50 LOG3[57]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 15:00:50 LOG5[57]: Connection closed: 5650 byte(s) sent to TLS, 2582 byte(s) sent to socket
2020.04.28 15:00:54 LOG5[59]: Service [https] accepted connection from 127.0.0.1:52647
2020.04.28 15:00:54 LOG5[60]: Service [https] accepted connection from 127.0.0.1:52648
2020.04.28 15:00:54 LOG3[59]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:00:54 LOG3[60]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:00:54 LOG5[59]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:00:54 LOG5[60]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:00:54 LOG5[61]: Service [https] accepted connection from 127.0.0.1:52649
2020.04.28 15:00:54 LOG3[61]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:00:54 LOG5[61]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:00:54 LOG5[62]: Service [https] accepted connection from 127.0.0.1:52650
2020.04.28 15:00:54 LOG3[62]: s_connect: connect ::1:8001: Connection refused (111)
2020.04.28 15:00:54 LOG5[62]: s_connect: connected 127.0.0.1:8001
2020.04.28 15:00:54 LOG5[62]: Service [https] connected remote server from 127.0.0.1:52652
2020.04.28 15:00:59 LOG5[63]: Service [https] accepted connection from 127.0.0.1:52655
2020.04.28 15:00:59 LOG3[63]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:00:59 LOG5[63]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:02:43 LOG3[62]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 15:02:43 LOG5[62]: Connection closed: 5680 byte(s) sent to TLS, 2582 byte(s) sent to socket
2020.04.28 15:02:48 LOG5[64]: Service [https] accepted connection from 127.0.0.1:52674
2020.04.28 15:02:48 LOG5[65]: Service [https] accepted connection from 127.0.0.1:52675
2020.04.28 15:02:48 LOG3[64]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:02:48 LOG3[65]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:02:48 LOG5[66]: Service [https] accepted connection from 127.0.0.1:52676
2020.04.28 15:02:48 LOG5[64]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:02:48 LOG5[65]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:02:48 LOG3[66]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:02:48 LOG5[66]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:02:48 LOG5[67]: Service [https] accepted connection from 127.0.0.1:52677
2020.04.28 15:02:48 LOG5[67]: s_connect: connected 127.0.0.1:8001
2020.04.28 15:02:48 LOG5[67]: Service [https] connected remote server from 127.0.0.1:52678
2020.04.28 15:02:53 LOG5[68]: Service [https] accepted connection from 127.0.0.1:52680
2020.04.28 15:02:53 LOG3[68]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:02:53 LOG5[68]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:11:50 LOG5[67]: Connection closed: 5683 byte(s) sent to TLS, 2582 byte(s) sent to socket
2020.04.28 15:11:50 LOG5[69]: Service [https] accepted connection from 127.0.0.1:52788
2020.04.28 15:11:50 LOG5[70]: Service [https] accepted connection from 127.0.0.1:52789
2020.04.28 15:11:50 LOG3[69]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:11:50 LOG3[70]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:11:50 LOG5[69]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:11:50 LOG5[70]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:11:50 LOG5[71]: Service [https] accepted connection from 127.0.0.1:52791
2020.04.28 15:11:50 LOG3[71]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:11:50 LOG5[71]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:11:50 LOG5[72]: Service [https] accepted connection from 127.0.0.1:52792
2020.04.28 15:11:50 LOG3[72]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:11:50 LOG5[72]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:11:58 LOG5[73]: Service [https] accepted connection from 127.0.0.1:52797
2020.04.28 15:11:58 LOG5[74]: Service [https] accepted connection from 127.0.0.1:52798
2020.04.28 15:11:58 LOG3[74]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:11:58 LOG3[73]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:11:58 LOG5[74]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:11:58 LOG5[73]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:11:58 LOG5[75]: Service [https] accepted connection from 127.0.0.1:52799
2020.04.28 15:11:58 LOG3[75]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:11:58 LOG5[75]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:11:58 LOG5[76]: Service [https] accepted connection from 127.0.0.1:52802
2020.04.28 15:11:58 LOG3[76]: s_connect: connect ::1:8001: Connection refused (111)
2020.04.28 15:11:58 LOG5[76]: s_connect: connected 127.0.0.1:8001
2020.04.28 15:11:58 LOG5[76]: Service [https] connected remote server from 127.0.0.1:52804
2020.04.28 15:11:58 LOG5[76]: Connection closed: 0 byte(s) sent to TLS, 578 byte(s) sent to socket
2020.04.28 15:11:58 LOG5[77]: Service [https] accepted connection from 127.0.0.1:52806
2020.04.28 15:11:58 LOG5[77]: s_connect: connected 127.0.0.1:8001
2020.04.28 15:11:58 LOG5[77]: Service [https] connected remote server from 127.0.0.1:52807
2020.04.28 15:11:59 LOG5[78]: Service [https] accepted connection from 127.0.0.1:52808
2020.04.28 15:11:59 LOG3[78]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:11:59 LOG5[78]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:12:59 LOG5[80]: Service [https] accepted connection from 127.0.0.1:52810
2020.04.28 15:12:59 LOG5[79]: Service [https] accepted connection from 127.0.0.1:52809
2020.04.28 15:12:59 LOG3[80]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:12:59 LOG3[79]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:12:59 LOG5[80]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:12:59 LOG5[79]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:12:59 LOG5[81]: Service [https] accepted connection from 127.0.0.1:52811
2020.04.28 15:12:59 LOG5[81]: s_connect: connected 127.0.0.1:8001
2020.04.28 15:12:59 LOG5[81]: Service [https] connected remote server from 127.0.0.1:52812
2020.04.28 15:13:16 LOG5[82]: Service [https] accepted connection from 127.0.0.1:52815
2020.04.28 15:13:16 LOG3[82]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:13:16 LOG5[82]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:13:24 LOG5[83]: Service [https] accepted connection from 127.0.0.1:52818
2020.04.28 15:13:24 LOG3[83]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:13:24 LOG5[83]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:22:40 LOG3[77]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 15:22:40 LOG3[81]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 15:22:40 LOG5[77]: Connection closed: 81311 byte(s) sent to TLS, 3135 byte(s) sent to socket
2020.04.28 15:22:40 LOG5[81]: Connection closed: 4957 byte(s) sent to TLS, 1259 byte(s) sent to socket
2020.04.28 15:22:46 LOG5[84]: Service [https] accepted connection from 127.0.0.1:52858
2020.04.28 15:22:46 LOG5[85]: Service [https] accepted connection from 127.0.0.1:52859
2020.04.28 15:22:46 LOG3[84]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:22:46 LOG3[85]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:22:46 LOG5[84]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:22:46 LOG5[85]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:22:46 LOG5[86]: Service [https] accepted connection from 127.0.0.1:52860
2020.04.28 15:22:46 LOG3[86]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:22:46 LOG5[86]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:22:47 LOG5[87]: Service [https] accepted connection from 127.0.0.1:52863
2020.04.28 15:22:47 LOG5[87]: s_connect: connected 127.0.0.1:8001
2020.04.28 15:22:47 LOG5[87]: Service [https] connected remote server from 127.0.0.1:52864
2020.04.28 15:22:47 LOG5[88]: Service [https] accepted connection from 127.0.0.1:52865
2020.04.28 15:22:47 LOG5[88]: s_connect: connected 127.0.0.1:8001
2020.04.28 15:22:47 LOG5[88]: Service [https] connected remote server from 127.0.0.1:52866
2020.04.28 15:23:38 LOG3[88]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 15:23:38 LOG3[87]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 15:23:38 LOG5[88]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:23:38 LOG5[87]: Connection closed: 5683 byte(s) sent to TLS, 2251 byte(s) sent to socket
2020.04.28 15:23:42 LOG5[89]: Service [https] accepted connection from 127.0.0.1:52887
2020.04.28 15:23:42 LOG5[90]: Service [https] accepted connection from 127.0.0.1:52888
2020.04.28 15:23:42 LOG3[89]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:23:42 LOG3[90]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:23:42 LOG5[89]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:23:42 LOG5[90]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:23:42 LOG5[91]: Service [https] accepted connection from 127.0.0.1:52889
2020.04.28 15:23:42 LOG3[91]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:23:42 LOG5[91]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:23:42 LOG5[92]: Service [https] accepted connection from 127.0.0.1:52892
2020.04.28 15:23:42 LOG3[92]: s_connect: connect ::1:8001: Connection refused (111)
2020.04.28 15:23:42 LOG5[92]: s_connect: connected 127.0.0.1:8001
2020.04.28 15:23:42 LOG5[92]: Service [https] connected remote server from 127.0.0.1:52894
2020.04.28 15:23:43 LOG5[93]: Service [https] accepted connection from 127.0.0.1:52895
2020.04.28 15:23:43 LOG5[93]: s_connect: connected 127.0.0.1:8001
2020.04.28 15:23:43 LOG5[93]: Service [https] connected remote server from 127.0.0.1:52896
2020.04.28 15:23:53 LOG5[93]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:24:57 LOG3[92]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 15:24:57 LOG5[92]: Connection closed: 5650 byte(s) sent to TLS, 2251 byte(s) sent to socket
2020.04.28 15:25:02 LOG5[94]: Service [https] accepted connection from 127.0.0.1:52915
2020.04.28 15:25:02 LOG5[95]: Service [https] accepted connection from 127.0.0.1:52916
2020.04.28 15:25:02 LOG3[94]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:25:02 LOG3[95]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:25:02 LOG5[94]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:25:02 LOG5[95]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:25:03 LOG5[96]: Service [https] accepted connection from 127.0.0.1:52917
2020.04.28 15:25:03 LOG3[96]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:25:03 LOG5[96]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:25:03 LOG5[97]: Service [https] accepted connection from 127.0.0.1:52920
2020.04.28 15:25:03 LOG5[97]: s_connect: connected 127.0.0.1:8001
2020.04.28 15:25:03 LOG5[97]: Service [https] connected remote server from 127.0.0.1:52921
2020.04.28 15:25:03 LOG5[98]: Service [https] accepted connection from 127.0.0.1:52922
2020.04.28 15:25:03 LOG5[98]: s_connect: connected 127.0.0.1:8001
2020.04.28 15:25:03 LOG5[98]: Service [https] connected remote server from 127.0.0.1:52923
2020.04.28 15:29:38 LOG5[98]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:31:41 LOG5[97]: Connection closed: 6409 byte(s) sent to TLS, 3460 byte(s) sent to socket
2020.04.28 15:31:41 LOG5[99]: Service [https] accepted connection from 127.0.0.1:52960
2020.04.28 15:31:41 LOG5[100]: Service [https] accepted connection from 127.0.0.1:52961
2020.04.28 15:31:41 LOG3[100]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:31:41 LOG3[99]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:31:41 LOG5[100]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:31:41 LOG5[99]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:31:42 LOG5[101]: Service [https] accepted connection from 127.0.0.1:52962
2020.04.28 15:31:42 LOG3[101]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:31:42 LOG5[101]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:31:42 LOG5[102]: Service [https] accepted connection from 127.0.0.1:52965
2020.04.28 15:31:42 LOG3[102]: s_connect: connect ::1:8001: Connection refused (111)
2020.04.28 15:31:42 LOG5[102]: s_connect: connected 127.0.0.1:8001
2020.04.28 15:31:42 LOG5[102]: Service [https] connected remote server from 127.0.0.1:52967
2020.04.28 15:31:42 LOG5[103]: Service [https] accepted connection from 127.0.0.1:52968
2020.04.28 15:31:42 LOG5[103]: s_connect: connected 127.0.0.1:8001
2020.04.28 15:31:42 LOG5[103]: Service [https] connected remote server from 127.0.0.1:52969
2020.04.28 15:32:08 LOG5[103]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:34:36 LOG3[102]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 15:34:36 LOG5[102]: Connection closed: 4753 byte(s) sent to TLS, 1144 byte(s) sent to socket
2020.04.28 15:44:20 LOG5[104]: Service [https] accepted connection from 127.0.0.1:53075
2020.04.28 15:44:20 LOG5[105]: Service [https] accepted connection from 127.0.0.1:53076
2020.04.28 15:44:20 LOG3[104]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:44:20 LOG3[105]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:44:20 LOG5[104]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:44:20 LOG5[105]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:44:20 LOG5[106]: Service [https] accepted connection from 127.0.0.1:53078
2020.04.28 15:44:20 LOG3[106]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:44:20 LOG5[106]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:44:21 LOG5[107]: Service [https] accepted connection from 127.0.0.1:53082
2020.04.28 15:44:21 LOG5[107]: s_connect: connected 127.0.0.1:8001
2020.04.28 15:44:21 LOG5[107]: Service [https] connected remote server from 127.0.0.1:53083
2020.04.28 15:44:21 LOG5[108]: Service [https] accepted connection from 127.0.0.1:53085
2020.04.28 15:44:21 LOG5[108]: s_connect: connected 127.0.0.1:8001
2020.04.28 15:44:21 LOG5[108]: Service [https] connected remote server from 127.0.0.1:53086
2020.04.28 15:45:55 LOG3[107]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 15:45:55 LOG3[108]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 15:45:55 LOG5[107]: Connection closed: 75206 byte(s) sent to TLS, 2593 byte(s) sent to socket
2020.04.28 15:45:55 LOG5[108]: Connection closed: 70121 byte(s) sent to TLS, 1323 byte(s) sent to socket
2020.04.28 15:48:35 LOG5[ui]: stunnel 5.44 on x86_64-pc-linux-gnu platform
2020.04.28 15:48:35 LOG5[ui]: Compiled with OpenSSL 1.1.0g  2 Nov 2017
2020.04.28 15:48:35 LOG5[ui]: Running  with OpenSSL 1.1.1  11 Sep 2018
2020.04.28 15:48:35 LOG5[ui]: Update OpenSSL shared libraries or rebuild stunnel
2020.04.28 15:48:35 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6,SYSTEMD TLS:ENGINE,FIPS,OCSP,PSK,SNI Auth:LIBWRAP
2020.04.28 15:48:35 LOG5[ui]: Reading configuration from file /mnt/d/VSCode/SeniorProject/cloud-backup/cloud_backup/stunnel/dev_https
2020.04.28 15:48:35 LOG5[ui]: UTF-8 byte order mark not detected
2020.04.28 15:48:35 LOG5[ui]: FIPS mode disabled
2020.04.28 15:48:35 LOG4[ui]: Insecure file permissions on stunnel/stunnel.pem
2020.04.28 15:48:35 LOG5[ui]: Configuration successful
2020.04.28 15:48:40 LOG5[109]: Service [https] accepted connection from 127.0.0.1:53108
2020.04.28 15:48:40 LOG5[110]: Service [https] accepted connection from 127.0.0.1:53109
2020.04.28 15:48:40 LOG3[109]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:48:40 LOG3[110]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:48:40 LOG5[109]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:48:40 LOG5[110]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:48:41 LOG5[111]: Service [https] accepted connection from 127.0.0.1:53110
2020.04.28 15:48:41 LOG3[111]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:48:41 LOG5[111]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:48:41 LOG5[112]: Service [https] accepted connection from 127.0.0.1:53113
2020.04.28 15:48:41 LOG3[112]: s_connect: connect ::1:8001: Connection refused (111)
2020.04.28 15:48:41 LOG5[112]: s_connect: connected 127.0.0.1:8001
2020.04.28 15:48:41 LOG5[112]: Service [https] connected remote server from 127.0.0.1:53115
2020.04.28 15:48:41 LOG5[113]: Service [https] accepted connection from 127.0.0.1:53116
2020.04.28 15:48:41 LOG5[113]: s_connect: connected 127.0.0.1:8001
2020.04.28 15:48:41 LOG5[113]: Service [https] connected remote server from 127.0.0.1:53117
2020.04.28 15:49:35 LOG5[cron]: Updating DH parameters
2020.04.28 15:49:38 LOG3[113]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 15:49:38 LOG5[113]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:49:38 LOG3[112]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 15:49:38 LOG5[112]: Connection closed: 5668 byte(s) sent to TLS, 2555 byte(s) sent to socket
2020.04.28 15:50:33 LOG5[114]: Service [https] accepted connection from 127.0.0.1:53140
2020.04.28 15:50:33 LOG3[114]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:50:33 LOG5[114]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:50:36 LOG5[115]: Service [https] accepted connection from 127.0.0.1:53142
2020.04.28 15:50:36 LOG3[115]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:50:36 LOG5[115]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:50:37 LOG5[116]: Service [https] accepted connection from 127.0.0.1:53146
2020.04.28 15:50:37 LOG5[117]: Service [https] accepted connection from 127.0.0.1:53147
2020.04.28 15:50:37 LOG3[116]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:50:37 LOG3[117]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:50:37 LOG5[116]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:50:37 LOG5[117]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:50:37 LOG5[118]: Service [https] accepted connection from 127.0.0.1:53148
2020.04.28 15:50:37 LOG3[118]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:50:37 LOG5[118]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:50:38 LOG5[119]: Service [https] accepted connection from 127.0.0.1:53151
2020.04.28 15:50:38 LOG5[119]: s_connect: connected 127.0.0.1:8001
2020.04.28 15:50:38 LOG5[119]: Service [https] connected remote server from 127.0.0.1:53152
2020.04.28 15:50:38 LOG5[120]: Service [https] accepted connection from 127.0.0.1:53153
2020.04.28 15:50:38 LOG5[120]: s_connect: connected 127.0.0.1:8001
2020.04.28 15:50:38 LOG5[120]: Service [https] connected remote server from 127.0.0.1:53154
2020.04.28 15:52:10 LOG5[cron]: DH parameters updated
2020.04.28 15:52:20 LOG5[120]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:54:16 LOG5[121]: Service [https] accepted connection from 127.0.0.1:53191
2020.04.28 15:54:16 LOG3[121]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:54:16 LOG5[121]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:54:23 LOG5[122]: Service [https] accepted connection from 127.0.0.1:53194
2020.04.28 15:54:23 LOG3[122]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:54:23 LOG5[122]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:54:40 LOG5[123]: Service [https] accepted connection from 127.0.0.1:53196
2020.04.28 15:54:40 LOG3[123]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:54:40 LOG5[123]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:54:47 LOG5[124]: Service [https] accepted connection from 127.0.0.1:53198
2020.04.28 15:54:47 LOG3[124]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:54:47 LOG5[124]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:55:07 LOG3[119]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 15:55:07 LOG5[119]: Connection closed: 18154 byte(s) sent to TLS, 10525 byte(s) sent to socket
2020.04.28 15:55:47 LOG5[125]: Service [https] accepted connection from 127.0.0.1:53214
2020.04.28 15:55:47 LOG5[126]: Service [https] accepted connection from 127.0.0.1:53215
2020.04.28 15:55:47 LOG3[125]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:55:47 LOG3[126]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:55:47 LOG5[125]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:55:47 LOG5[126]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:55:47 LOG5[127]: Service [https] accepted connection from 127.0.0.1:53216
2020.04.28 15:55:47 LOG3[127]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:55:47 LOG5[127]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:55:48 LOG5[128]: Service [https] accepted connection from 127.0.0.1:53219
2020.04.28 15:55:48 LOG3[128]: s_connect: connect ::1:8001: Connection refused (111)
2020.04.28 15:55:48 LOG5[128]: s_connect: connected 127.0.0.1:8001
2020.04.28 15:55:48 LOG5[128]: Service [https] connected remote server from 127.0.0.1:53221
2020.04.28 15:55:48 LOG5[129]: Service [https] accepted connection from 127.0.0.1:53222
2020.04.28 15:55:48 LOG5[129]: s_connect: connected 127.0.0.1:8001
2020.04.28 15:55:48 LOG5[129]: Service [https] connected remote server from 127.0.0.1:53223
2020.04.28 15:56:19 LOG3[128]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 15:56:19 LOG3[129]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 15:56:19 LOG5[128]: Connection closed: 3727 byte(s) sent to TLS, 2080 byte(s) sent to socket
2020.04.28 15:56:19 LOG5[129]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:56:48 LOG5[130]: Service [https] accepted connection from 127.0.0.1:53235
2020.04.28 15:56:48 LOG5[131]: Service [https] accepted connection from 127.0.0.1:53236
2020.04.28 15:56:48 LOG3[130]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:56:48 LOG3[131]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:56:48 LOG5[130]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:56:48 LOG5[131]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:56:48 LOG5[132]: Service [https] accepted connection from 127.0.0.1:53237
2020.04.28 15:56:48 LOG3[132]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:56:48 LOG5[132]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:56:48 LOG5[133]: Service [https] accepted connection from 127.0.0.1:53240
2020.04.28 15:56:48 LOG5[133]: s_connect: connected 127.0.0.1:8001
2020.04.28 15:56:48 LOG5[133]: Service [https] connected remote server from 127.0.0.1:53241
2020.04.28 15:56:48 LOG5[134]: Service [https] accepted connection from 127.0.0.1:53242
2020.04.28 15:56:48 LOG5[134]: s_connect: connected 127.0.0.1:8001
2020.04.28 15:56:48 LOG5[134]: Service [https] connected remote server from 127.0.0.1:53243
2020.04.28 15:57:10 LOG3[133]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 15:57:10 LOG3[134]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 15:57:10 LOG5[133]: Connection closed: 8486 byte(s) sent to TLS, 3469 byte(s) sent to socket
2020.04.28 15:57:10 LOG5[134]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:57:13 LOG5[135]: Service [https] accepted connection from 127.0.0.1:53256
2020.04.28 15:57:13 LOG5[136]: Service [https] accepted connection from 127.0.0.1:53257
2020.04.28 15:57:13 LOG3[135]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:57:13 LOG3[136]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:57:13 LOG5[135]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:57:13 LOG5[136]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:57:13 LOG5[137]: Service [https] accepted connection from 127.0.0.1:53258
2020.04.28 15:57:13 LOG3[137]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:57:13 LOG5[137]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:57:14 LOG5[138]: Service [https] accepted connection from 127.0.0.1:53261
2020.04.28 15:57:14 LOG3[138]: s_connect: connect ::1:8001: Connection refused (111)
2020.04.28 15:57:14 LOG5[138]: s_connect: connected 127.0.0.1:8001
2020.04.28 15:57:14 LOG5[138]: Service [https] connected remote server from 127.0.0.1:53263
2020.04.28 15:57:14 LOG5[139]: Service [https] accepted connection from 127.0.0.1:53264
2020.04.28 15:57:14 LOG5[139]: s_connect: connected 127.0.0.1:8001
2020.04.28 15:57:14 LOG5[139]: Service [https] connected remote server from 127.0.0.1:53265
2020.04.28 15:57:28 LOG3[138]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 15:57:28 LOG3[139]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 15:57:28 LOG5[138]: Connection closed: 2986 byte(s) sent to TLS, 784 byte(s) sent to socket
2020.04.28 15:57:28 LOG5[139]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:57:39 LOG5[140]: Service [https] accepted connection from 127.0.0.1:53278
2020.04.28 15:57:39 LOG5[141]: Service [https] accepted connection from 127.0.0.1:53279
2020.04.28 15:57:39 LOG3[140]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:57:39 LOG3[141]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:57:39 LOG5[140]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:57:39 LOG5[141]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:57:39 LOG5[142]: Service [https] accepted connection from 127.0.0.1:53280
2020.04.28 15:57:39 LOG3[142]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 15:57:39 LOG5[142]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 15:57:39 LOG5[143]: Service [https] accepted connection from 127.0.0.1:53283
2020.04.28 15:57:39 LOG5[143]: s_connect: connected 127.0.0.1:8001
2020.04.28 15:57:39 LOG5[143]: Service [https] connected remote server from 127.0.0.1:53284
2020.04.28 15:57:39 LOG5[144]: Service [https] accepted connection from 127.0.0.1:53285
2020.04.28 15:57:39 LOG5[144]: s_connect: connected 127.0.0.1:8001
2020.04.28 15:57:39 LOG5[144]: Service [https] connected remote server from 127.0.0.1:53286
2020.04.28 15:59:38 LOG5[144]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:00:25 LOG3[143]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:00:25 LOG5[143]: Connection closed: 8488 byte(s) sent to TLS, 3469 byte(s) sent to socket
2020.04.28 16:01:51 LOG5[145]: Service [https] accepted connection from 127.0.0.1:53345
2020.04.28 16:01:51 LOG5[146]: Service [https] accepted connection from 127.0.0.1:53346
2020.04.28 16:01:51 LOG3[145]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:01:51 LOG3[146]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:01:51 LOG5[145]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:01:51 LOG5[146]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:01:52 LOG5[147]: Service [https] accepted connection from 127.0.0.1:53347
2020.04.28 16:01:52 LOG3[147]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:01:52 LOG5[147]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:01:52 LOG5[148]: Service [https] accepted connection from 127.0.0.1:53350
2020.04.28 16:01:52 LOG3[148]: s_connect: connect ::1:8001: Connection refused (111)
2020.04.28 16:01:52 LOG5[148]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:01:52 LOG5[148]: Service [https] connected remote server from 127.0.0.1:53352
2020.04.28 16:01:52 LOG5[149]: Service [https] accepted connection from 127.0.0.1:53353
2020.04.28 16:01:52 LOG5[149]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:01:52 LOG5[149]: Service [https] connected remote server from 127.0.0.1:53354
2020.04.28 16:02:50 LOG3[149]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:02:50 LOG3[148]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:02:50 LOG5[149]: Connection closed: 67563 byte(s) sent to TLS, 2087 byte(s) sent to socket
2020.04.28 16:02:50 LOG5[148]: Connection closed: 72444 byte(s) sent to TLS, 3532 byte(s) sent to socket
2020.04.28 16:02:52 LOG5[150]: Service [https] accepted connection from 127.0.0.1:53370
2020.04.28 16:02:52 LOG5[151]: Service [https] accepted connection from 127.0.0.1:53371
2020.04.28 16:02:52 LOG3[150]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:02:52 LOG3[151]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:02:52 LOG5[150]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:02:52 LOG5[151]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:02:52 LOG5[152]: Service [https] accepted connection from 127.0.0.1:53372
2020.04.28 16:02:52 LOG3[152]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:02:52 LOG5[152]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:02:53 LOG5[153]: Service [https] accepted connection from 127.0.0.1:53375
2020.04.28 16:02:53 LOG5[153]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:02:53 LOG5[153]: Service [https] connected remote server from 127.0.0.1:53376
2020.04.28 16:02:53 LOG5[154]: Service [https] accepted connection from 127.0.0.1:53377
2020.04.28 16:02:53 LOG5[154]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:02:53 LOG5[154]: Service [https] connected remote server from 127.0.0.1:53378
2020.04.28 16:03:03 LOG5[154]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:03:03 LOG5[155]: Service [https] accepted connection from 127.0.0.1:53382
2020.04.28 16:03:03 LOG3[155]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:03:03 LOG5[155]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:04:41 LOG3[153]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:04:41 LOG5[153]: Connection closed: 72326 byte(s) sent to TLS, 3475 byte(s) sent to socket
2020.04.28 16:05:06 LOG5[156]: Service [https] accepted connection from 127.0.0.1:53407
2020.04.28 16:05:06 LOG5[157]: Service [https] accepted connection from 127.0.0.1:53408
2020.04.28 16:05:06 LOG3[156]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:05:06 LOG3[157]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:05:06 LOG5[156]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:05:06 LOG5[157]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:05:06 LOG5[158]: Service [https] accepted connection from 127.0.0.1:53409
2020.04.28 16:05:06 LOG3[158]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:05:06 LOG5[158]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:05:06 LOG5[159]: Service [https] accepted connection from 127.0.0.1:53412
2020.04.28 16:05:06 LOG5[159]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:05:06 LOG5[159]: Service [https] connected remote server from 127.0.0.1:53413
2020.04.28 16:05:07 LOG5[160]: Service [https] accepted connection from 127.0.0.1:53414
2020.04.28 16:05:07 LOG5[160]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:05:07 LOG5[160]: Service [https] connected remote server from 127.0.0.1:53415
2020.04.28 16:05:58 LOG3[160]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:05:58 LOG3[159]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:05:58 LOG5[160]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:05:58 LOG5[159]: Connection closed: 68453 byte(s) sent to TLS, 3475 byte(s) sent to socket
2020.04.28 16:06:02 LOG5[161]: Service [https] accepted connection from 127.0.0.1:53430
2020.04.28 16:06:02 LOG5[162]: Service [https] accepted connection from 127.0.0.1:53431
2020.04.28 16:06:02 LOG3[161]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:06:02 LOG3[162]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:06:02 LOG5[161]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:06:02 LOG5[162]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:06:03 LOG5[163]: Service [https] accepted connection from 127.0.0.1:53432
2020.04.28 16:06:03 LOG3[163]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:06:03 LOG5[163]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:06:03 LOG5[164]: Service [https] accepted connection from 127.0.0.1:53435
2020.04.28 16:06:03 LOG3[164]: s_connect: connect ::1:8001: Connection refused (111)
2020.04.28 16:06:03 LOG5[164]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:06:03 LOG5[164]: Service [https] connected remote server from 127.0.0.1:53437
2020.04.28 16:06:03 LOG5[165]: Service [https] accepted connection from 127.0.0.1:53438
2020.04.28 16:06:03 LOG5[165]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:06:03 LOG5[165]: Service [https] connected remote server from 127.0.0.1:53439
2020.04.28 16:06:57 LOG3[165]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:06:57 LOG3[164]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:06:57 LOG5[165]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:06:57 LOG5[164]: Connection closed: 72438 byte(s) sent to TLS, 3475 byte(s) sent to socket
2020.04.28 16:07:01 LOG5[166]: Service [https] accepted connection from 127.0.0.1:53454
2020.04.28 16:07:01 LOG5[167]: Service [https] accepted connection from 127.0.0.1:53455
2020.04.28 16:07:01 LOG3[166]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:07:01 LOG3[167]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:07:01 LOG5[166]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:07:01 LOG5[167]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:07:01 LOG5[168]: Service [https] accepted connection from 127.0.0.1:53456
2020.04.28 16:07:01 LOG3[168]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:07:01 LOG5[168]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:07:02 LOG5[169]: Service [https] accepted connection from 127.0.0.1:53459
2020.04.28 16:07:02 LOG5[169]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:07:02 LOG5[169]: Service [https] connected remote server from 127.0.0.1:53460
2020.04.28 16:07:02 LOG5[170]: Service [https] accepted connection from 127.0.0.1:53462
2020.04.28 16:07:02 LOG5[170]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:07:02 LOG5[170]: Service [https] connected remote server from 127.0.0.1:53463
2020.04.28 16:08:38 LOG3[170]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:08:38 LOG3[169]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:08:38 LOG5[170]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:08:38 LOG5[169]: Connection closed: 66952 byte(s) sent to TLS, 790 byte(s) sent to socket
2020.04.28 16:08:44 LOG5[171]: Service [https] accepted connection from 127.0.0.1:53479
2020.04.28 16:08:44 LOG5[172]: Service [https] accepted connection from 127.0.0.1:53480
2020.04.28 16:08:44 LOG3[171]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:08:44 LOG3[172]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:08:44 LOG5[171]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:08:44 LOG5[172]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:08:44 LOG5[173]: Service [https] accepted connection from 127.0.0.1:53481
2020.04.28 16:08:44 LOG3[173]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:08:44 LOG5[173]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:08:44 LOG5[174]: Service [https] accepted connection from 127.0.0.1:53484
2020.04.28 16:08:44 LOG3[174]: s_connect: connect ::1:8001: Connection refused (111)
2020.04.28 16:08:44 LOG5[174]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:08:44 LOG5[174]: Service [https] connected remote server from 127.0.0.1:53486
2020.04.28 16:08:45 LOG5[175]: Service [https] accepted connection from 127.0.0.1:53487
2020.04.28 16:08:45 LOG5[175]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:08:45 LOG5[175]: Service [https] connected remote server from 127.0.0.1:53488
2020.04.28 16:09:07 LOG5[175]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:09:41 LOG5[176]: Service [https] accepted connection from 127.0.0.1:53497
2020.04.28 16:09:41 LOG3[176]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:09:41 LOG5[176]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:09:49 LOG5[177]: Service [https] accepted connection from 127.0.0.1:53501
2020.04.28 16:09:49 LOG3[177]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:09:49 LOG5[177]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:09:50 LOG5[178]: Service [https] accepted connection from 127.0.0.1:53504
2020.04.28 16:09:50 LOG3[178]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:09:50 LOG5[178]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:09:50 LOG5[179]: Service [https] accepted connection from 127.0.0.1:53506
2020.04.28 16:09:50 LOG5[179]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:09:50 LOG5[179]: Service [https] connected remote server from 127.0.0.1:53507
2020.04.28 16:10:17 LOG3[179]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:10:17 LOG3[174]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:10:17 LOG5[179]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:10:17 LOG5[174]: Connection closed: 167481 byte(s) sent to TLS, 7062 byte(s) sent to socket
2020.04.28 16:10:20 LOG5[180]: Service [https] accepted connection from 127.0.0.1:53524
2020.04.28 16:10:20 LOG5[181]: Service [https] accepted connection from 127.0.0.1:53525
2020.04.28 16:10:20 LOG3[180]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:10:20 LOG3[181]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:10:20 LOG5[180]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:10:20 LOG5[181]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:10:20 LOG5[182]: Service [https] accepted connection from 127.0.0.1:53526
2020.04.28 16:10:20 LOG3[182]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:10:20 LOG5[182]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:10:20 LOG5[183]: Service [https] accepted connection from 127.0.0.1:53529
2020.04.28 16:10:20 LOG5[183]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:10:20 LOG5[183]: Service [https] connected remote server from 127.0.0.1:53530
2020.04.28 16:10:20 LOG5[184]: Service [https] accepted connection from 127.0.0.1:53531
2020.04.28 16:10:20 LOG5[184]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:10:20 LOG5[184]: Service [https] connected remote server from 127.0.0.1:53532
2020.04.28 16:11:08 LOG3[183]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:11:08 LOG3[184]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:11:08 LOG5[183]: Connection closed: 8824 byte(s) sent to TLS, 4166 byte(s) sent to socket
2020.04.28 16:11:08 LOG5[184]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:11:09 LOG5[185]: Service [https] accepted connection from 127.0.0.1:53553
2020.04.28 16:11:09 LOG5[186]: Service [https] accepted connection from 127.0.0.1:53554
2020.04.28 16:11:09 LOG3[185]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:11:09 LOG3[186]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:11:09 LOG5[185]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:11:09 LOG5[186]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:11:09 LOG5[187]: Service [https] accepted connection from 127.0.0.1:53555
2020.04.28 16:11:09 LOG3[187]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:11:09 LOG5[187]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:11:09 LOG5[188]: Service [https] accepted connection from 127.0.0.1:53558
2020.04.28 16:11:09 LOG3[188]: s_connect: connect ::1:8001: Connection refused (111)
2020.04.28 16:11:09 LOG5[188]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:11:09 LOG5[188]: Service [https] connected remote server from 127.0.0.1:53560
2020.04.28 16:11:09 LOG5[189]: Service [https] accepted connection from 127.0.0.1:53561
2020.04.28 16:11:09 LOG5[189]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:11:09 LOG5[189]: Service [https] connected remote server from 127.0.0.1:53562
2020.04.28 16:11:46 LOG3[188]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:11:46 LOG5[188]: Connection closed: 8890 byte(s) sent to TLS, 4181 byte(s) sent to socket
2020.04.28 16:11:46 LOG3[189]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:11:46 LOG5[189]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:13:02 LOG5[190]: Service [https] accepted connection from 127.0.0.1:53619
2020.04.28 16:13:02 LOG5[191]: Service [https] accepted connection from 127.0.0.1:53620
2020.04.28 16:13:02 LOG3[190]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:13:02 LOG3[191]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:13:02 LOG5[190]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:13:02 LOG5[191]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:13:02 LOG5[192]: Service [https] accepted connection from 127.0.0.1:53621
2020.04.28 16:13:02 LOG3[192]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:13:02 LOG5[192]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:13:03 LOG5[193]: Service [https] accepted connection from 127.0.0.1:53625
2020.04.28 16:13:03 LOG5[193]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:13:03 LOG5[193]: Service [https] connected remote server from 127.0.0.1:53626
2020.04.28 16:13:03 LOG5[194]: Service [https] accepted connection from 127.0.0.1:53627
2020.04.28 16:13:03 LOG5[194]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:13:03 LOG5[194]: Service [https] connected remote server from 127.0.0.1:53628
2020.04.28 16:13:31 LOG3[193]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:13:31 LOG3[194]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:13:31 LOG5[193]: Connection closed: 8890 byte(s) sent to TLS, 4181 byte(s) sent to socket
2020.04.28 16:13:31 LOG5[194]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:13:34 LOG5[195]: Service [https] accepted connection from 127.0.0.1:53640
2020.04.28 16:13:34 LOG5[196]: Service [https] accepted connection from 127.0.0.1:53641
2020.04.28 16:13:34 LOG3[195]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:13:34 LOG3[196]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:13:34 LOG5[195]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:13:34 LOG5[196]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:13:35 LOG5[197]: Service [https] accepted connection from 127.0.0.1:53642
2020.04.28 16:13:35 LOG3[197]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:13:35 LOG5[197]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:13:35 LOG5[198]: Service [https] accepted connection from 127.0.0.1:53645
2020.04.28 16:13:35 LOG3[198]: s_connect: connect ::1:8001: Connection refused (111)
2020.04.28 16:13:35 LOG5[198]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:13:35 LOG5[198]: Service [https] connected remote server from 127.0.0.1:53647
2020.04.28 16:13:35 LOG5[199]: Service [https] accepted connection from 127.0.0.1:53648
2020.04.28 16:13:35 LOG5[199]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:13:35 LOG5[199]: Service [https] connected remote server from 127.0.0.1:53649
2020.04.28 16:13:55 LOG3[198]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:13:55 LOG3[199]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:13:55 LOG5[198]: Connection closed: 8115 byte(s) sent to TLS, 4128 byte(s) sent to socket
2020.04.28 16:13:55 LOG5[199]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:13:59 LOG5[200]: Service [https] accepted connection from 127.0.0.1:53661
2020.04.28 16:13:59 LOG5[201]: Service [https] accepted connection from 127.0.0.1:53662
2020.04.28 16:13:59 LOG3[200]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:13:59 LOG3[201]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:13:59 LOG5[200]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:13:59 LOG5[201]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:13:59 LOG5[202]: Service [https] accepted connection from 127.0.0.1:53663
2020.04.28 16:13:59 LOG3[202]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:13:59 LOG5[202]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:13:59 LOG5[203]: Service [https] accepted connection from 127.0.0.1:53666
2020.04.28 16:13:59 LOG5[203]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:13:59 LOG5[203]: Service [https] connected remote server from 127.0.0.1:53667
2020.04.28 16:14:00 LOG5[204]: Service [https] accepted connection from 127.0.0.1:53668
2020.04.28 16:14:00 LOG5[204]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:14:00 LOG5[204]: Service [https] connected remote server from 127.0.0.1:53669
2020.04.28 16:14:38 LOG5[204]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:15:39 LOG3[203]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:15:39 LOG5[203]: Connection closed: 10097 byte(s) sent to TLS, 6709 byte(s) sent to socket
2020.04.28 16:15:47 LOG5[205]: Service [https] accepted connection from 127.0.0.1:53692
2020.04.28 16:15:47 LOG5[206]: Service [https] accepted connection from 127.0.0.1:53693
2020.04.28 16:15:47 LOG3[205]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:15:47 LOG3[206]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:15:47 LOG5[205]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:15:47 LOG5[206]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:15:47 LOG5[207]: Service [https] accepted connection from 127.0.0.1:53695
2020.04.28 16:15:47 LOG3[207]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:15:47 LOG5[207]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:15:47 LOG5[208]: Service [https] accepted connection from 127.0.0.1:53696
2020.04.28 16:15:47 LOG3[208]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:15:47 LOG5[208]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:15:47 LOG5[209]: Service [https] accepted connection from 127.0.0.1:53699
2020.04.28 16:15:47 LOG5[209]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:15:47 LOG5[209]: Service [https] connected remote server from 127.0.0.1:53700
2020.04.28 16:15:48 LOG5[210]: Service [https] accepted connection from 127.0.0.1:53703
2020.04.28 16:15:48 LOG5[210]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:15:48 LOG5[210]: Service [https] connected remote server from 127.0.0.1:53704
2020.04.28 16:15:48 LOG5[211]: Service [https] accepted connection from 127.0.0.1:53705
2020.04.28 16:15:48 LOG3[211]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:15:48 LOG5[211]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:15:48 LOG5[212]: Service [https] accepted connection from 127.0.0.1:53706
2020.04.28 16:15:48 LOG3[212]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:15:48 LOG5[212]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:16:25 LOG3[210]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:16:25 LOG3[209]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:16:25 LOG5[210]: Connection closed: 76370 byte(s) sent to TLS, 2764 byte(s) sent to socket
2020.04.28 16:16:25 LOG5[209]: Connection closed: 77739 byte(s) sent to TLS, 2786 byte(s) sent to socket
2020.04.28 16:16:31 LOG5[213]: Service [https] accepted connection from 127.0.0.1:53724
2020.04.28 16:16:31 LOG5[214]: Service [https] accepted connection from 127.0.0.1:53725
2020.04.28 16:16:31 LOG3[213]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:16:31 LOG3[214]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:16:31 LOG5[213]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:16:31 LOG5[214]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:16:31 LOG5[215]: Service [https] accepted connection from 127.0.0.1:53726
2020.04.28 16:16:31 LOG3[215]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:16:31 LOG5[215]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:16:31 LOG5[216]: Service [https] accepted connection from 127.0.0.1:53729
2020.04.28 16:16:31 LOG3[216]: s_connect: connect ::1:8001: Connection refused (111)
2020.04.28 16:16:31 LOG5[216]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:16:31 LOG5[216]: Service [https] connected remote server from 127.0.0.1:53731
2020.04.28 16:16:32 LOG5[217]: Service [https] accepted connection from 127.0.0.1:53732
2020.04.28 16:16:32 LOG5[217]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:16:32 LOG5[217]: Service [https] connected remote server from 127.0.0.1:53733
2020.04.28 16:17:14 LOG3[216]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:17:14 LOG3[217]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:17:14 LOG5[216]: Connection closed: 76387 byte(s) sent to TLS, 3406 byte(s) sent to socket
2020.04.28 16:17:14 LOG5[217]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:24:53 LOG5[218]: Service [https] accepted connection from 127.0.0.1:53847
2020.04.28 16:24:53 LOG5[219]: Service [https] accepted connection from 127.0.0.1:53848
2020.04.28 16:24:53 LOG3[218]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:24:53 LOG3[219]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:24:53 LOG5[218]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:24:53 LOG5[219]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:24:54 LOG5[220]: Service [https] accepted connection from 127.0.0.1:53849
2020.04.28 16:24:54 LOG3[220]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:24:54 LOG5[220]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:24:54 LOG5[221]: Service [https] accepted connection from 127.0.0.1:53852
2020.04.28 16:24:54 LOG5[221]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:24:54 LOG5[221]: Service [https] connected remote server from 127.0.0.1:53853
2020.04.28 16:24:54 LOG5[222]: Service [https] accepted connection from 127.0.0.1:53855
2020.04.28 16:24:54 LOG5[222]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:24:54 LOG5[222]: Service [https] connected remote server from 127.0.0.1:53856
2020.04.28 16:25:31 LOG3[222]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:25:31 LOG3[221]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:25:31 LOG5[222]: Connection closed: 67750 byte(s) sent to TLS, 2087 byte(s) sent to socket
2020.04.28 16:25:31 LOG5[221]: Connection closed: 67878 byte(s) sent to TLS, 2144 byte(s) sent to socket
2020.04.28 16:25:35 LOG5[223]: Service [https] accepted connection from 127.0.0.1:53872
2020.04.28 16:25:35 LOG5[224]: Service [https] accepted connection from 127.0.0.1:53873
2020.04.28 16:25:35 LOG3[223]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:25:35 LOG3[224]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:25:35 LOG5[223]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:25:35 LOG5[224]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:25:36 LOG5[225]: Service [https] accepted connection from 127.0.0.1:53874
2020.04.28 16:25:36 LOG3[225]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:25:36 LOG5[225]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:25:36 LOG5[226]: Service [https] accepted connection from 127.0.0.1:53877
2020.04.28 16:25:36 LOG3[226]: s_connect: connect ::1:8001: Connection refused (111)
2020.04.28 16:25:36 LOG5[226]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:25:36 LOG5[226]: Service [https] connected remote server from 127.0.0.1:53879
2020.04.28 16:25:36 LOG5[227]: Service [https] accepted connection from 127.0.0.1:53881
2020.04.28 16:25:36 LOG5[227]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:25:36 LOG5[227]: Service [https] connected remote server from 127.0.0.1:53882
2020.04.28 16:27:57 LOG3[227]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:27:57 LOG3[226]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:27:57 LOG5[227]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:27:57 LOG5[226]: Connection closed: 160369 byte(s) sent to TLS, 4066 byte(s) sent to socket
2020.04.28 16:28:11 LOG5[228]: Service [https] accepted connection from 127.0.0.1:53909
2020.04.28 16:28:11 LOG5[229]: Service [https] accepted connection from 127.0.0.1:53910
2020.04.28 16:28:11 LOG3[228]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:28:11 LOG3[229]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:28:11 LOG5[228]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:28:11 LOG5[229]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:28:11 LOG5[230]: Service [https] accepted connection from 127.0.0.1:53911
2020.04.28 16:28:11 LOG3[230]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:28:11 LOG5[230]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:28:11 LOG5[231]: Service [https] accepted connection from 127.0.0.1:53915
2020.04.28 16:28:11 LOG5[231]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:28:11 LOG5[231]: Service [https] connected remote server from 127.0.0.1:53916
2020.04.28 16:28:11 LOG5[232]: Service [https] accepted connection from 127.0.0.1:53917
2020.04.28 16:28:11 LOG5[232]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:28:11 LOG5[232]: Service [https] connected remote server from 127.0.0.1:53918
2020.04.28 16:29:19 LOG3[231]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:29:19 LOG3[232]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:29:19 LOG5[231]: Connection closed: 160409 byte(s) sent to TLS, 4066 byte(s) sent to socket
2020.04.28 16:29:19 LOG5[232]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:29:35 LOG5[233]: Service [https] accepted connection from 127.0.0.1:53951
2020.04.28 16:29:35 LOG5[234]: Service [https] accepted connection from 127.0.0.1:53952
2020.04.28 16:29:35 LOG3[233]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:29:35 LOG3[234]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:29:35 LOG5[233]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:29:35 LOG5[234]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:29:35 LOG5[235]: Service [https] accepted connection from 127.0.0.1:53953
2020.04.28 16:29:35 LOG3[235]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:29:35 LOG5[235]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:29:35 LOG5[236]: Service [https] accepted connection from 127.0.0.1:53956
2020.04.28 16:29:35 LOG3[236]: s_connect: connect ::1:8001: Connection refused (111)
2020.04.28 16:29:35 LOG5[236]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:29:35 LOG5[236]: Service [https] connected remote server from 127.0.0.1:53958
2020.04.28 16:29:36 LOG5[237]: Service [https] accepted connection from 127.0.0.1:53959
2020.04.28 16:29:36 LOG5[237]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:29:36 LOG5[237]: Service [https] connected remote server from 127.0.0.1:53960
2020.04.28 16:29:57 LOG3[236]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:29:57 LOG3[237]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:29:57 LOG5[236]: Connection closed: 76595 byte(s) sent to TLS, 3406 byte(s) sent to socket
2020.04.28 16:29:57 LOG5[237]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:30:03 LOG5[238]: Service [https] accepted connection from 127.0.0.1:53977
2020.04.28 16:30:03 LOG5[239]: Service [https] accepted connection from 127.0.0.1:53978
2020.04.28 16:30:03 LOG3[238]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:30:03 LOG3[239]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:30:03 LOG5[238]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:30:03 LOG5[239]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:30:04 LOG5[240]: Service [https] accepted connection from 127.0.0.1:53979
2020.04.28 16:30:04 LOG3[240]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:30:04 LOG5[240]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:30:04 LOG5[241]: Service [https] accepted connection from 127.0.0.1:53982
2020.04.28 16:30:04 LOG5[241]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:30:04 LOG5[241]: Service [https] connected remote server from 127.0.0.1:53983
2020.04.28 16:30:04 LOG5[242]: Service [https] accepted connection from 127.0.0.1:53984
2020.04.28 16:30:04 LOG5[242]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:30:04 LOG5[242]: Service [https] connected remote server from 127.0.0.1:53985
2020.04.28 16:31:24 LOG3[241]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:31:24 LOG5[241]: Connection closed: 77189 byte(s) sent to TLS, 4767 byte(s) sent to socket
2020.04.28 16:31:24 LOG3[242]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:31:24 LOG5[242]: Connection closed: 76950 byte(s) sent to TLS, 783 byte(s) sent to socket
2020.04.28 16:31:31 LOG5[243]: Service [https] accepted connection from 127.0.0.1:54003
2020.04.28 16:31:31 LOG5[244]: Service [https] accepted connection from 127.0.0.1:54004
2020.04.28 16:31:31 LOG3[243]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:31:31 LOG3[244]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:31:31 LOG5[243]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:31:31 LOG5[244]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:31:32 LOG5[245]: Service [https] accepted connection from 127.0.0.1:54006
2020.04.28 16:31:32 LOG3[245]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:31:32 LOG5[245]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:31:32 LOG5[246]: Service [https] accepted connection from 127.0.0.1:54008
2020.04.28 16:31:32 LOG3[246]: s_connect: connect ::1:8001: Connection refused (111)
2020.04.28 16:31:32 LOG5[246]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:31:32 LOG5[246]: Service [https] connected remote server from 127.0.0.1:54010
2020.04.28 16:31:32 LOG5[247]: Service [https] accepted connection from 127.0.0.1:54011
2020.04.28 16:31:32 LOG5[247]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:31:32 LOG5[247]: Service [https] connected remote server from 127.0.0.1:54012
2020.04.28 16:33:17 LOG5[247]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:33:34 LOG3[246]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:33:34 LOG5[246]: Connection closed: 76464 byte(s) sent to TLS, 3406 byte(s) sent to socket
2020.04.28 16:33:42 LOG5[248]: Service [https] accepted connection from 127.0.0.1:54038
2020.04.28 16:33:42 LOG5[249]: Service [https] accepted connection from 127.0.0.1:54039
2020.04.28 16:33:42 LOG3[248]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:33:42 LOG3[249]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:33:42 LOG5[248]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:33:42 LOG5[249]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:33:42 LOG5[250]: Service [https] accepted connection from 127.0.0.1:54040
2020.04.28 16:33:42 LOG3[250]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:33:42 LOG5[250]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:33:42 LOG5[251]: Service [https] accepted connection from 127.0.0.1:54043
2020.04.28 16:33:42 LOG5[251]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:33:42 LOG5[251]: Service [https] connected remote server from 127.0.0.1:54044
2020.04.28 16:33:42 LOG5[252]: Service [https] accepted connection from 127.0.0.1:54045
2020.04.28 16:33:42 LOG5[252]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:33:42 LOG5[252]: Service [https] connected remote server from 127.0.0.1:54046
2020.04.28 16:35:04 LOG3[251]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:35:04 LOG3[252]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:35:04 LOG5[251]: Connection closed: 76464 byte(s) sent to TLS, 3406 byte(s) sent to socket
2020.04.28 16:35:04 LOG5[252]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:35:11 LOG5[253]: Service [https] accepted connection from 127.0.0.1:54070
2020.04.28 16:35:11 LOG5[254]: Service [https] accepted connection from 127.0.0.1:54071
2020.04.28 16:35:11 LOG3[253]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:35:11 LOG3[254]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:35:11 LOG5[253]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:35:11 LOG5[254]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:35:12 LOG5[255]: Service [https] accepted connection from 127.0.0.1:54072
2020.04.28 16:35:12 LOG3[255]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:35:12 LOG5[255]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:35:12 LOG5[256]: Service [https] accepted connection from 127.0.0.1:54075
2020.04.28 16:35:12 LOG3[256]: s_connect: connect ::1:8001: Connection refused (111)
2020.04.28 16:35:12 LOG5[256]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:35:12 LOG5[256]: Service [https] connected remote server from 127.0.0.1:54077
2020.04.28 16:35:12 LOG5[257]: Service [https] accepted connection from 127.0.0.1:54078
2020.04.28 16:35:12 LOG5[257]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:35:12 LOG5[257]: Service [https] connected remote server from 127.0.0.1:54079
2020.04.28 16:35:33 LOG3[257]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:35:33 LOG3[256]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:35:33 LOG5[257]: Connection closed: 76458 byte(s) sent to TLS, 3406 byte(s) sent to socket
2020.04.28 16:35:33 LOG5[256]: Connection closed: 76586 byte(s) sent to TLS, 3501 byte(s) sent to socket
2020.04.28 16:36:52 LOG5[258]: Service [https] accepted connection from 127.0.0.1:54120
2020.04.28 16:36:52 LOG5[259]: Service [https] accepted connection from 127.0.0.1:54121
2020.04.28 16:36:52 LOG3[258]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:36:52 LOG3[259]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:36:52 LOG5[258]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:36:52 LOG5[259]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:36:52 LOG5[260]: Service [https] accepted connection from 127.0.0.1:54122
2020.04.28 16:36:52 LOG3[260]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:36:52 LOG5[260]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:36:52 LOG5[261]: Service [https] accepted connection from 127.0.0.1:54125
2020.04.28 16:36:52 LOG5[261]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:36:52 LOG5[261]: Service [https] connected remote server from 127.0.0.1:54126
2020.04.28 16:36:53 LOG5[262]: Service [https] accepted connection from 127.0.0.1:54127
2020.04.28 16:36:53 LOG5[262]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:36:53 LOG5[262]: Service [https] connected remote server from 127.0.0.1:54128
2020.04.28 16:38:33 LOG3[262]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:38:33 LOG3[261]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:38:33 LOG5[262]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:38:33 LOG5[261]: Connection closed: 76465 byte(s) sent to TLS, 3406 byte(s) sent to socket
2020.04.28 16:38:59 LOG5[263]: Service [https] accepted connection from 127.0.0.1:54161
2020.04.28 16:38:59 LOG5[264]: Service [https] accepted connection from 127.0.0.1:54162
2020.04.28 16:38:59 LOG3[263]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:38:59 LOG3[264]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:38:59 LOG5[263]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:38:59 LOG5[264]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:38:59 LOG5[265]: Service [https] accepted connection from 127.0.0.1:54163
2020.04.28 16:38:59 LOG3[265]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:38:59 LOG5[265]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:38:59 LOG5[266]: Service [https] accepted connection from 127.0.0.1:54166
2020.04.28 16:38:59 LOG3[266]: s_connect: connect ::1:8001: Connection refused (111)
2020.04.28 16:38:59 LOG5[266]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:38:59 LOG5[266]: Service [https] connected remote server from 127.0.0.1:54168
2020.04.28 16:38:59 LOG5[267]: Service [https] accepted connection from 127.0.0.1:54169
2020.04.28 16:38:59 LOG5[267]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:38:59 LOG5[267]: Service [https] connected remote server from 127.0.0.1:54170
2020.04.28 16:39:40 LOG5[267]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:40:40 LOG3[266]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:40:40 LOG5[266]: Connection closed: 76458 byte(s) sent to TLS, 3406 byte(s) sent to socket
2020.04.28 16:40:45 LOG5[268]: Service [https] accepted connection from 127.0.0.1:54194
2020.04.28 16:40:45 LOG5[269]: Service [https] accepted connection from 127.0.0.1:54195
2020.04.28 16:40:45 LOG3[268]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:40:45 LOG3[269]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:40:45 LOG5[268]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:40:45 LOG5[269]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:40:46 LOG5[270]: Service [https] accepted connection from 127.0.0.1:54196
2020.04.28 16:40:46 LOG3[270]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:40:46 LOG5[270]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:40:46 LOG5[271]: Service [https] accepted connection from 127.0.0.1:54199
2020.04.28 16:40:46 LOG5[271]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:40:46 LOG5[271]: Service [https] connected remote server from 127.0.0.1:54200
2020.04.28 16:40:46 LOG5[272]: Service [https] accepted connection from 127.0.0.1:54201
2020.04.28 16:40:46 LOG5[272]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:40:46 LOG5[272]: Service [https] connected remote server from 127.0.0.1:54202
2020.04.28 16:41:16 LOG3[272]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:41:16 LOG3[271]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:41:16 LOG5[272]: Connection closed: 101544 byte(s) sent to TLS, 3406 byte(s) sent to socket
2020.04.28 16:41:16 LOG5[271]: Connection closed: 101672 byte(s) sent to TLS, 3501 byte(s) sent to socket
2020.04.28 16:41:28 LOG5[273]: Service [https] accepted connection from 127.0.0.1:54222
2020.04.28 16:41:28 LOG5[274]: Service [https] accepted connection from 127.0.0.1:54223
2020.04.28 16:41:28 LOG3[273]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:41:28 LOG3[274]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:41:28 LOG5[273]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:41:28 LOG5[274]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:41:28 LOG5[275]: Service [https] accepted connection from 127.0.0.1:54224
2020.04.28 16:41:28 LOG3[275]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:41:28 LOG5[275]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:41:29 LOG5[276]: Service [https] accepted connection from 127.0.0.1:54227
2020.04.28 16:41:29 LOG3[276]: s_connect: connect ::1:8001: Connection refused (111)
2020.04.28 16:41:29 LOG5[276]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:41:29 LOG5[276]: Service [https] connected remote server from 127.0.0.1:54229
2020.04.28 16:41:29 LOG5[277]: Service [https] accepted connection from 127.0.0.1:54230
2020.04.28 16:41:29 LOG5[277]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:41:29 LOG5[277]: Service [https] connected remote server from 127.0.0.1:54231
2020.04.28 16:42:19 LOG3[276]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:42:19 LOG3[277]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:42:19 LOG5[276]: Connection closed: 101544 byte(s) sent to TLS, 3406 byte(s) sent to socket
2020.04.28 16:42:19 LOG5[277]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:43:36 LOG5[278]: Service [https] accepted connection from 127.0.0.1:54266
2020.04.28 16:43:36 LOG5[279]: Service [https] accepted connection from 127.0.0.1:54267
2020.04.28 16:43:36 LOG3[278]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:43:36 LOG3[279]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:43:36 LOG5[278]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:43:36 LOG5[279]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:43:36 LOG5[280]: Service [https] accepted connection from 127.0.0.1:54268
2020.04.28 16:43:36 LOG3[280]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:43:36 LOG5[280]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:43:37 LOG5[281]: Service [https] accepted connection from 127.0.0.1:54271
2020.04.28 16:43:37 LOG5[281]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:43:37 LOG5[281]: Service [https] connected remote server from 127.0.0.1:54272
2020.04.28 16:43:37 LOG5[282]: Service [https] accepted connection from 127.0.0.1:54273
2020.04.28 16:43:37 LOG5[282]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:43:37 LOG5[282]: Service [https] connected remote server from 127.0.0.1:54274
2020.04.28 16:44:00 LOG3[281]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:44:00 LOG3[282]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:44:00 LOG5[281]: Connection closed: 82552 byte(s) sent to TLS, 3406 byte(s) sent to socket
2020.04.28 16:44:00 LOG5[282]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:44:07 LOG5[283]: Service [https] accepted connection from 127.0.0.1:54291
2020.04.28 16:44:07 LOG5[284]: Service [https] accepted connection from 127.0.0.1:54292
2020.04.28 16:44:07 LOG3[283]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:44:07 LOG3[284]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:44:07 LOG5[283]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:44:07 LOG5[284]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:44:07 LOG5[285]: Service [https] accepted connection from 127.0.0.1:54293
2020.04.28 16:44:07 LOG3[285]: SSL_accept: 14094416: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown
2020.04.28 16:44:07 LOG5[285]: Connection reset: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:44:07 LOG5[286]: Service [https] accepted connection from 127.0.0.1:54296
2020.04.28 16:44:07 LOG3[286]: s_connect: connect ::1:8001: Connection refused (111)
2020.04.28 16:44:07 LOG5[286]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:44:07 LOG5[286]: Service [https] connected remote server from 127.0.0.1:54298
2020.04.28 16:44:07 LOG5[287]: Service [https] accepted connection from 127.0.0.1:54299
2020.04.28 16:44:07 LOG5[287]: s_connect: connected 127.0.0.1:8001
2020.04.28 16:44:07 LOG5[287]: Service [https] connected remote server from 127.0.0.1:54300
2020.04.28 16:44:38 LOG5[287]: Connection closed: 0 byte(s) sent to TLS, 0 byte(s) sent to socket
2020.04.28 16:46:16 LOG3[286]: transfer: s_poll_wait: TIMEOUTclose exceeded: closing
2020.04.28 16:46:16 LOG5[286]: Connection closed: 6902 byte(s) sent to TLS, 3978 byte(s) sent to socket
2020.04.28 17:03:29 LOG5[ui]: stunnel 5.44 on x86_64-pc-linux-gnu platform
2020.04.28 17:03:29 LOG5[ui]: Compiled with OpenSSL 1.1.0g  2 Nov 2017
2020.04.28 17:03:29 LOG5[ui]: Running  with OpenSSL 1.1.1  11 Sep 2018
2020.04.28 17:03:29 LOG5[ui]: Update OpenSSL shared libraries or rebuild stunnel
2020.04.28 17:03:29 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6,SYSTEMD TLS:ENGINE,FIPS,OCSP,PSK,SNI Auth:LIBWRAP
2020.04.28 17:03:29 LOG5[ui]: Reading configuration from file /mnt/d/VSCode/SeniorProject/cloud-backup/cloud_backup/stunnel/dev_https
2020.04.28 17:03:29 LOG5[ui]: UTF-8 byte order mark not detected
2020.04.28 17:03:29 LOG5[ui]: FIPS mode disabled
2020.04.28 17:03:29 LOG4[ui]: Insecure file permissions on stunnel/stunnel.pem
2020.04.28 17:03:29 LOG5[ui]: Configuration successful
2020.04.28 17:03:53 LOG5[ui]: stunnel 5.44 on x86_64-pc-linux-gnu platform
2020.04.28 17:03:53 LOG5[ui]: Compiled with OpenSSL 1.1.0g  2 Nov 2017
2020.04.28 17:03:53 LOG5[ui]: Running  with OpenSSL 1.1.1  11 Sep 2018
2020.04.28 17:03:53 LOG5[ui]: Update OpenSSL shared libraries or rebuild stunnel
2020.04.28 17:03:53 LOG5[ui]: Threading:PTHREAD Sockets:POLL,IPv6,SYSTEMD TLS:ENGINE,FIPS,OCSP,PSK,SNI Auth:LIBWRAP
2020.04.28 17:03:53 LOG5[ui]: Reading configuration from file /mnt/d/VSCode/SeniorProject/cloud-backup/cloud_backup/stunnel/dev_https
2020.04.28 17:03:53 LOG5[ui]: UTF-8 byte order mark not detected
2020.04.28 17:03:53 LOG5[ui]: FIPS mode disabled
2020.04.28 17:03:53 LOG4[ui]: Insecure file permissions on stunnel/stunnel.pem
2020.04.28 17:03:53 LOG5[ui]: Configuration successful
2020.04.28 17:04:29 LOG5[cron]: Updating DH parameters
2020.04.28 17:04:33 LOG5[cron]: DH parameters updated
2020.04.28 17:04:53 LOG5[cron]: Updating DH parameters
2020.04.28 17:05:06 LOG5[cron]: DH parameters updated
